service: hr-vacations-api 
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
functions:
  getEmployee:
    handler: employeeHandler.getEmployee
    events:
    - http:
        path: /employee/{employeeId}
        method: get
        cors: true
        request:
          template:
            application/json: '{ "employeeId" : "$input.params(''employeeId'')" }'
          parameters:
            paths:
              employeeId: true
        response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')
  createEmployee:
    handler: createEmployeeHandler.createEmployee
    events:
    - http:
        path: /employee
        method: post
        cors: true
        response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')
  updateEmployee:
    handler: updateEmployeeHandler.updateEmployee
    events:
    - http:
        path: /employee
        method: PUT
        cors: true
        response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')
  getEmployees:
    handler: employeesHandler.getEmployees
    events:
    - http:
        path: /employees
        method: get
        cors: true
        response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$')
